cart/urls.py
from django.urls import path
from .views import *
app_name= 'cart'
urlpatterns = [path( '' , cart_detail, name='cart_detail'),
               path('add/<int:product_id>/', cart_add, name='cart_add'),
               path('remove/<int:product_id>/', cart_remove,name='cart_remove'),
]

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'
urlpatterns = [
    path('',Index.as_view(),name='index'),
    path('category/<int:cat_id>/', show_category, name='category'),
    path('post/<int:pk>/', ShowPost.as_view(), name='post'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path("search/", search.as_view(), name='search'),

]

onlainshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from onlainshop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('main.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.urls import reverse

class Product(models.Model):
    name = models.CharField(max_length=255,verbose_name="Название товара")
    description = models.TextField(blank=True,verbose_name="Описание")
    price = models.FloatField(default=0,verbose_name='Цена')
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/",verbose_name="Фото")
    time_create = models.DateTimeField(auto_now_add=True,verbose_name="Время создания")
    time_update = models.DateTimeField(auto_now=True,verbose_name="Время изменения")
    is_published = models.BooleanField(default=True,verbose_name="Публикация")
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, null=True,verbose_name="Категории")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['-time_create', 'name']

class Category(models.Model):
    name_cat = models.CharField(max_length=100, db_index=True,verbose_name="Категория")


    def __str__(self):
        return self.name_cat

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_id': self.pk})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['id']

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False, initial=False,
                                widget=forms.HiddenInput)

main/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

cart/views.py
from django.shortcuts import render
from django.shortcuts import redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from main.models import Product, Category
from .cart import Cart
from .forms import CartAddProductForm


# Create your views here.
@login_required
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

@login_required
def cart_detail(request):
    cart = Cart(request)
    cats = Category.objects.all()
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart,'cats':cats})

main/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy

from .forms import *
from .models import *
from django.views.generic import ListView,DetailView,CreateView
from cart.forms import CartAddProductForm

class Index(ListView):
    paginate_by = 5
    model = Product
    template_name = 'main/index.html'
    context_object_name = 'products'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        cats = Category.objects.all()
        cart_product_form = CartAddProductForm()
        context['cats'] = cats
        context['cart_product_form']=cart_product_form
        return context

    def get_queryset(self):
        return Product.objects.filter(is_published=True)

'''def index(request):
    cats = Category.objects.all()
    products = Product.objects.filter(is_published=True)
    paginator = Paginator(products, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    cart_product_form = CartAddProductForm()
    return render(request, 'main/index.html', {
        'page_obj': page_obj,
        'cats' : cats,
        'products' : products,
        'cart_product_form' : cart_product_form

    })'''

def show_category(request, cat_id):
    posts = Product.objects.filter(cat_id=cat_id)
    cats = Category.objects.all()
    cart_product_form = CartAddProductForm()
    context = {'posts': posts,'cats':cats,'cart_product_form':cart_product_form}
    return render(request, 'main/category.html', context=context)

class ShowPost(DetailView):
    model = Product
    template_name = 'main/post.html'
    context_object_name = 'post'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        cats = Category.objects.all()
        cart_product_form = CartAddProductForm()
        context['cart_product_form'] = cart_product_form
        context['cats'] = cats
        return context




class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'main/register.html'
    success_url = reverse_lazy('main:login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Регистрация"
        cats = Category.objects.all()
        context['cats'] = cats
        return context

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('main:index')



class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'main/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        cats = Category.objects.all()
        context['cats'] = cats
        context['title'] = "Авторизация"
        return context

    def get_success_url(self):
        return reverse_lazy('main:index')

def logout_user(request):
    logout(request)
    return redirect('main:login')

class search(ListView):
    model = Product
    template_name = 'main/search.html'
    context_object_name = 'post'

    def get_queryset(self):
        return Product.objects.filter(name__iregex=self.request.GET.get("search"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        cats = Category.objects.all()
        context['cats'] = cats
        return context

cart/templates/cart/detail.html
{% extends "main/base.html" %}


{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
    <h1>Ваша корзина</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Фото</th>
            <th>Товар</th>
            <th>Количество</th>
            <th>Удалить|</th>
            <th>Цена за единицу</th>
            <th>Цена</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                    {% if product.photo %}{{ product.photo.url }}{% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>
    <form action="{% url "cart:cart_add" product.id %}"
          method="post">
        {{ item.update_quantity_form.quantity }}
        {{ item.update_quantity_form.update }}
        <input type="submit" value="Update">
        {% csrf_token %}
    </form>
</td>
                    <td>
                        <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                    </td>
                    <td class="num">Руб.{{ item.price }}</td>
                    <td class="num">Руб.{{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td colspan="4"></td>
            <td class="num">ОБЩАЯ СТОИМОСТЬ : Руб.{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "main:index" %}" class="button light">Продолжить покупки</a>
    </p>
{% endblock %}

main/templates/main/base.html
{% load bootstrap4 %}
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
        content="width=device-width, initial-scale=l, shrink-to-fit=no">
        <title>{% block title %} {%  endblock title %} </title>
        <link type="text/css" href="{% static 'main/css/styles.css' %}" rel="stylesheet" />
        {% bootstrap_css %}

        {% bootstrap_javascript jquery='slim' %}
    </head>
    <body class="container-fluid">
        <header class="mb-4">
            <center><h1 class="display-l 1ех1-сеп1ег">Каталог</h1></center>
        </header>
        <div class="row">
            <ul class="col nav justify-content-end border">
                		{% if request.user.is_authenticated %}
                <li class="last"> {{user.username}} | <a href="{% url 'main:logout' %}">Выйти</a></li>
                   {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'main:register' %}">Регистрация</a></li>

                    <li class="nav-item"><a class="nav-link" href="{% url 'main:login' %}">Bxoд</a></li>
                {% endif %}
                           <form action="{% url 'main:search' %}" method="get">
  <input type="text" name="search">
  <button type="sumbit">Поиск</button>
</form>
                </ul>
            </div>
    <!--строка корзины-->
        <center>
            <div class="cart">
        {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                <a href="{% url "cart:cart_detail" %}">Ваша корзина:</a>
                    {{ total_items }}товар{{ total_items|pluralize:'а'}},
                    Руб.{{ cart.get_total_price }}

            {% else %}
                Your cart is empty.
            {% endif %}
        {% endwith %}
    </div>
        </center>
            <div class="row">
                <nav class="col-md-auto nav flex-column border">
                    <center><a class="nav-link root"
                       href="{% url 'main:index' %}"><h2>Главная</h2></a></center>
                    <center><h5>Категории</h5></center>
                    {% for c in cats %}
                    <a class="nav-link" href="{% url 'main:category' c.pk %}">{{c}}</a>
                    {% endfor %}
                </nav>
                <section class="col border py-2">
                    {% bootstrap_messages %}
                    {% block content %}
                    {% endblock %}
                </section>
            </div>
    <nav>
    <ul>
        {% for p in page_obj.paginator.page_range %}
        <li>
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endfor %}
    </ul>
</nav>
        </body>
</html>

main/templates/main/category.html
{% extends 'main/base.html' %}


{% block title %} fddfdf {%  endblock title %}



{% block content %}

<center>
{%  for i in posts %}
    <p><h2><a href="{% url 'main:post' i.pk %}">{{ i.name }}</a></h2></p>
{% if i.photo %}
<p><img class="img" src="{{i.photo.url}}"></p>
{% endif %}
    <form action="{% url 'cart:cart_add' i.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart">
    </form>
    <hr>
    {% endfor %}

</center>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block title %} Главная {%  endblock title %}
{% block content %}
<center>
{% for product in products %}
<p><h2><a href="{% url 'main:post' product.pk %}">{{ product.name }}</a></h2></p>
    <p class="price">Руб.{{ product.price }}</p>
{% if product.photo %}
<p><img class="img" src="{{product.photo.url}}"></p>
{% endif  %}
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart">
    </form>
    <hr>
{% endfor %}
</center>

{% endblock %}

main/templates/main/login.html
{% extends 'main/base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}
<div class="form-error">{{ form.non_field_errors }}</div>

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}
    <button type="submit">Войти</button>
</form>

{% endblock %}

main/templates/main/post.html
{% extends 'main/base.html' %}

{% block content %}
<center>
<h1>{{post.name}}</h1>

{% if post.photo %}
<p><img class="img-article-left" src="{{post.photo.url}}"></p>
{% endif %}
    <form action="{% url 'cart:cart_add' post.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart">
    </form>
<p>ОПИСАНИЕ ТОВАРА: {{post.description}}</p>

    <p>ЦЕНА: {{post.price}}руб.</p>
</center>
{% endblock %}

main/templates/main/register.html
{% extends 'main/base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Регистрация</button>
</form>

{% endblock %}

main/templates/main/search.html
{% extends 'main/base.html' %}
{% block content %}
{% if post %}
    <center><h1>Результаты найдены</h1></center>
    <br>

{% for i in post %}


<center><h2><a href="/post/{{ i.pk }}">{{ i.name }}</a></h2>
{% if i.photo %}
<p><img class="img" src="{{i.photo.url}}"></p>
{% endif  %}
    <hr>
</center>
{% endfor %}
    {% else %}
<center><h1>ПО ВАШЕМУ ЗАПРОСУ НИЧЕГО НЕ НАЙДЕНО</h1></center>
{% endif %}
  </br>
{% endblock %}